server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/network_db?allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
    username: ENC(PWu0QZMimWB0juSsNBfwTQ==)
    password: ENC(62tVsgv8KdaO7f+lI79ZF6h99njiI82z)
  liquibase:
    change-log: /db/changelog/changelog.yml
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate
  rsocket:
    server:
      port:
ws:
  server:
    port: 1111
    host: 0.0.0.0
registration:
  confirm:
    need: false
    url: "http://localhost:8086/api/v1/account/registration_complete"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

external:
  vk:
    id: ENC(m7rHhgvZf1a3XykimmtX9A==)
    token: ENC(0FWZ/Ebbh5M0GV/ZD8TcXU1ISRbcusF9MrjiZsUnR4Vf4Hv8l7sp32S4w/KWqNsnLI7ppZCPy3ZztKJxXLGkhpBEkJXeEZpE6NFIDCts6BY=)
  cloudinary:
    cloud: ENC(Vfhff27NWtbJpMagmXDrAPdoUn5Wl0BP)
    key: ENC(Dw9PMgrkxd0Q7YTIBowaLFI/ixt2nvHf)
    secret: ENC(hQVnqsRAm3jW1tjWc3zDAOu19ppToSJ7czBD5CHa0E6coGq36y7wVA==)
  mail:
    key: ENC(K7d4bRWHYCdbITscwoIqPIi9SZx6rbteqan1VTjzniHFyBzcsTb5rogbtnljp3hh)
    secret: ENC(GXKUX11aEp43FY4B8CpX79OmUI9ryLyY6yHSLBz33RSWAFf47jYk+c1SlLYUuKdG)
    from: ENC(H4dZAhFspV/470tWbOY7Jk6mllp/EYJYns4oVTKaDqHkMqYtrtBK8Q==)

jasypt:
  encryptor:
    bean: encryptorBean

cors:
  - http://localhost:8081/
  - http://127.0.0.1:8081/
  - http://localhost/
  - http://127.0.0.1/
  - http://195.234.208.58/
  - http://localhost:80/
  - http://127.0.0.1:80/
  - http://195.234.208.58:80/
  - http://www.zeronenetwork.design/
  - http://10.186.0.2:8086/
  - http://10.186.0.2/%22