image: kroncosta/qmis_1101:228
stages:
  - build

build:
  artifacts:
    paths:
      - /builds/javapro18/javapro18_team_backend/jars/test/*.jar # путь для хранения артефакта
  only: # условия выполнения
    - merge_request
    - dev
  except:
    - tags
  stage: build
  when: always
  before_script: # подключение к ссерверу по SSH
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $DEV_HOST >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo pwd
    - mvn clean package -Pserver-build
    -
#    - ssh $DEV_USER@$DEV_HOST "[ ! -f $DEV_APP_PATH/social-network-0.0.1-SNAPSHOT.jar ] || mv $DEV_APP_PATH/app_name.jar $DEV_APP_PATH/app_name-build-$CI_PIPELINE_ID.jar"
    - scp jars/social-network-0.0.1-SNAPSHOT.jar $DEV_USER@$DEV_HOST:$DEV_APP_PATH/
  cache:
    paths:
      - ./target
      - ./.m2