<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.skillbox</groupId>
    <artifactId>java-pro</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <properties>
        <spring-boot.version>2.3.7.RELEASE</spring-boot.version>
        <log4j.version>2.14.0</log4j.version>
        <spring-boot-admin.version>2.3.1</spring-boot-admin.version>
        <java.version>16</java.version>
        <maven.compiler.target>16</maven.compiler.target>
        <maven.compiler.source>16</maven.compiler.source>
    </properties>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.6</version>
    </parent>

    <modules>
        <module>social-network</module>
        <module>zero-cloud-config</module>
        <module>microservice</module>
    </modules>

    <profiles>
        <profile>
            <id>prod</id>
            <build>
                <directory>./jars/test/</directory>
            </build>
        </profile>
    </profiles>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-checkstyle-plugin</artifactId>
                    <version>3.6.0</version>
                    <configuration>
                        <propertyExpansion>
                            suppressionFile=/checkstyle/suppressions.xml
                            suppressionXpathFile=/checkstyle/suppressions-xpath.xml
                        </propertyExpansion>
                        <suppressionsLocation>baselines/checkstyle-suppressions.xml</suppressionsLocation>
                        <consoleOutput>true</consoleOutput>
                        <failsOnError>true</failsOnError>
                        <failOnViolation>true</failOnViolation>
                        <excludes>**/main/resources/**/*</excludes>
                        <excludes>**/generated/**/*</excludes>
                        <excludes>**/generated-sources/**/*</excludes>
                        <includeTestSourceDirectory>false</includeTestSourceDirectory>
                    </configuration>
                    <dependencies>
                        <!-- checkstyle -->
                        <dependency>
                            <groupId>com.puppycrawl.tools</groupId>
                            <artifactId>checkstyle</artifactId>
                            <version>10.21.2</version>
                        </dependency>
                    </dependencies>
                    <executions>
                        <execution>
                            <id>checkstyle-validate-sources</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>com.github.spotbugs</groupId>
                    <artifactId>spotbugs-maven-plugin</artifactId>
                    <version>4.8.6.6</version>
                    <configuration>
                        <failOnError>true</failOnError>
                        <effort>Max</effort>
                        <threshold>Low</threshold>
                        <excludeFilterFile>baselines/spotbugs-exclude.xml</excludeFilterFile>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-pmd-plugin</artifactId>
                    <version>3.26.0</version>
                    <configuration>
                        <verbose>true</verbose>
                        <linkXRef>false</linkXRef>
                        <failOnViolation>true</failOnViolation>
                        <rulesets>
                            <ruleset>baselines/pmd-baseline-ruleset.xml</ruleset>
                        </rulesets>
                        <excludes>
                            <exclude>**/generated/*.java</exclude>
                            <exclude>**/generated-sources/*.java</exclude>
                        </excludes>
                        <excludeRoots>
                            <excludeRoot>target/classes</excludeRoot>
                            <excludeRoot>target/generated-sources</excludeRoot>
                        </excludeRoots>
                    </configuration>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>check</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>2.5.4</version>
                <configuration>
                    <jvmArguments>-Dspring.application.admin.enabled=true</jvmArguments>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                    <outputDirectory>./jars</outputDirectory>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>16</source>
                    <target>16</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

