server:
  port: 8086
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/network_db?allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
    username: user
    password: password
  liquibase:
    change-log: /db/changelog/changelog.yml
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: validate

  mail:
    host: smtp.yandex.ru
    username: ivan.zukkel.mailsender@yandex.ru
    password: vdgclvhfzrqcjqvc
    port: 465
    protocol: smtps
mail:
  debug: true


vk:
  id: ENC(m7rHhgvZf1a3XykimmtX9A==)
  token: ENC(0FWZ/Ebbh5M0GV/ZD8TcXU1ISRbcusF9MrjiZsUnR4Vf4Hv8l7sp32S4w/KWqNsnLI7ppZCPy3ZztKJxXLGkhpBEkJXeEZpE6NFIDCts6BY=)

jasypt:
  encryptor:
    bean: encryptorBean