spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/network_db?allowPublicKeyRetrieval=true&useSSL=false&&serverTimezone=UTC
    username: user
    password: password
  liquibase:
    change-log: /db/changelog/changelog.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none
