{
 "title": "Loki",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "log",
   "type": "logs",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}"
    }
   ]
  },
  {
   "title": "Error",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"varlogs\"}|=\"ERROR\""
    }
   ]
  },
  {
   "title": "Error",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"}|=\"ERROR\"[180s])"
    }
   ]
  },
  {
   "title": "Error",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"}|=\"ERROR\"[5m])",
     "resolution": 1
    }
   ]
  },
  {
   "title": "Liquibase failed",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count_over_time({job=\"varlogs\"}|=\"Liquibase failed to start\"[5m])"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 4, "x": 20, "y": 25 } }
 ]
}