apiVersion: 1

datasources:
  - name: Prometheus
    label: Prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    isDefault: true
  - name: Loki
    label: Loki
    type: loki
    access: proxy
    url: loki:3100
    isDefault: false
